import { InterviewPipeline, PipelineStage } from '@/types/interview-pipeline';

// Mock pipeline data for demonstration
export function createMockPipeline(): InterviewPipeline {
  const now = new Date();
  const stageId = () => `stage-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

  const stages: PipelineStage[] = [
    {
      id: stageId(),
      category: 'application',
      name: 'Application',
      nameZh: '申请',
      status: 'completed',
      subStatus: 'resume_passed',
      owner: 'hr',
      ownerName: '李明 (HR)',
      completedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      notes: '简历背景匹配度高，有相关行业经验',
      order: 1,
      isRequired: true,
      createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: stageId(),
      category: 'hr_screening',
      name: 'HR Screening',
      nameZh: 'HR筛选',
      status: 'completed',
      subStatus: 'hr_screen_passed',
      owner: 'hr',
      ownerName: '李明 (HR)',
      scheduledEvent: {
        dateTime: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: 'Asia/Shanghai',
        duration: 30,
        meetingLink: 'https://zoom.us/j/123456789',
      },
      completedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      notes: '沟通顺畅，薪资期望在预算范围内，最快可1个月内入职',
      order: 2,
      isRequired: true,
      createdAt: new Date(now.getTime() - 13 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: stageId(),
      category: 'interview_round',
      name: 'Round 1 - Technical',
      nameZh: '一面-技术',
      status: 'completed',
      subStatus: 'passed',
      owner: 'interviewer',
      ownerName: '张伟 (Tech Lead)',
      roundType: 'technical',
      roundNumber: 1,
      scheduledEvent: {
        dateTime: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: 'Asia/Shanghai',
        duration: 60,
        meetingLink: 'https://zoom.us/j/987654321',
      },
      completedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      feedback: [
        {
          interviewerId: 'int-001',
          interviewerName: '张伟',
          interviewerTitle: 'Tech Lead',
          rating: 4,
          recommendation: 'hire',
          strengths: ['系统设计能力强', '代码质量意识好', '有大型项目经验'],
          concerns: ['对新技术栈需要一定学习时间'],
          notes: '整体表现不错，建议进入下一轮',
          submittedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
      ],
      order: 3,
      createdAt: new Date(now.getTime() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: stageId(),
      category: 'assessment',
      name: 'Take-home Assignment',
      nameZh: '笔试作业',
      status: 'completed',
      subStatus: 'assessment_passed',
      owner: 'candidate',
      assessmentType: 'take_home',
      deadline: {
        dateTime: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: 'Asia/Shanghai',
      },
      completedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      notes: '提前一天提交，代码结构清晰，文档完整',
      order: 4,
      createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: stageId(),
      category: 'interview_round',
      name: 'Round 2 - Business',
      nameZh: '二面-业务',
      status: 'completed',
      subStatus: 'passed',
      owner: 'hiring_manager',
      ownerName: '王强 (HM)',
      roundType: 'business',
      roundNumber: 2,
      scheduledEvent: {
        dateTime: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: 'Asia/Shanghai',
        duration: 45,
        location: '上海办公室 - 会议室A',
      },
      completedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      feedback: [
        {
          interviewerId: 'int-002',
          interviewerName: '王强',
          interviewerTitle: 'Hiring Manager',
          rating: 5,
          recommendation: 'strong_hire',
          strengths: ['业务理解深刻', '沟通表达清晰', '有团队管理潜力'],
          concerns: [],
          notes: '非常优秀，强烈推荐',
          submittedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
      ],
      order: 5,
      createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: stageId(),
      category: 'interview_round',
      name: 'Round 3 - Cross-team',
      nameZh: '三面-交叉',
      status: 'in_progress',
      subStatus: 'scheduled',
      owner: 'interviewer',
      ownerName: '陈静 (Product Director)',
      roundType: 'cross_team',
      roundNumber: 3,
      scheduledEvent: {
        dateTime: new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
        timezone: 'America/New_York',
        duration: 60,
        meetingLink: 'https://zoom.us/j/111222333',
      },
      riskTags: ['competing_offer'],
      notes: '候选人提到收到其他公司offer，需加快流程',
      order: 6,
      createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: stageId(),
      category: 'final_decision',
      name: 'Final Decision',
      nameZh: '终审',
      status: 'upcoming',
      subStatus: 'hm_approval_pending',
      owner: 'hiring_manager',
      riskTags: ['timeline_delay', 'hc_risk'],
      notes: '待交叉面试完成后进入终审',
      order: 7,
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: stageId(),
      category: 'offer',
      name: 'Offer',
      nameZh: 'Offer',
      status: 'upcoming',
      owner: 'hr',
      riskTags: ['salary_gap'],
      order: 8,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: stageId(),
      category: 'pre_onboarding',
      name: 'Pre-onboarding',
      nameZh: '入职前准备',
      status: 'upcoming',
      owner: 'hr',
      order: 9,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
    {
      id: stageId(),
      category: 'onboarding',
      name: 'Onboarding',
      nameZh: '入职',
      status: 'upcoming',
      owner: 'hr',
      order: 10,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
    },
  ];

  return {
    id: 'pipeline-001',
    jobId: 'job-001',
    candidateId: 'candidate-001',
    candidate: {
      id: 'candidate-001',
      name: '赵晓明',
      email: 'xiaoming.zhao@email.com',
      phone: '+86 138-0000-0001',
      currentCompany: '某互联网大厂',
      currentTitle: 'Senior Software Engineer',
      yearsOfExperience: 6,
      salaryExpectation: {
        min: 50000,
        max: 65000,
        currency: 'CNY',
      },
      noticePeriod: '1个月',
      preferredStartDate: new Date(now.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
      source: 'linkedin',
      tags: ['高潜力', '技术专家', '有管理经验'],
    },
    companyName: '字节跳动',
    roleTitle: 'Senior Backend Engineer',
    department: 'Engineering - Data Platform',
    location: 'CN',
    stages,
    currentStageId: stages[5].id, // Round 3
    overallStatus: 'active',
    globalRiskTags: ['competing_offer', 'timeline_delay'],
    daysInPipeline: 14,
    conversionProbability: 0.75,
    appliedAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    lastActivityAt: now.toISOString(),
    createdBy: 'recruiter-001',
    assignedRecruiter: '李明',
    assignedHM: '王强',
  };
}
